Done Dz_11
Wasil-P/Python_lessons pull request #4
Opened 2023-03-30 14:08 UTC by Wasil-P

Дзень добры.
Праверце, калі ласка, калі будзе час.
Нешта цяжкавата даецца ОПП, пагэтаму так позна высылаю.
Задачку я так і не дабіў. Прашу вас глянуць, што раблю не так?
Галоўны затык з захаваннем гісторыі і яе вывадам. 
Пераназначаю у атрыбут self.last_operation унутры класа BankAcc пры кожнай аперацыі залічэнны\зняцця сродкаў. Ствараю экзэмпляр last_operation_history і праз яго хачу выцягнуць атрыбут унутры Класа OperationsHistory. Але па выніку не працуе.
Можа не туды капаю увогуле?

2023-03-31 14:09 UTC, vimoro requested changes

2023-03-31 14:09 UTC, vimoro commented on Dz_11.py
> +        self.last_operation = ()
вот тут назови поле history и храни список объектов типа BankAccountHistory

2023-03-31 14:09 UTC, vimoro commented on Dz_11.py
> +        self.last_operation = (f"Replenishment of the balance {self.balance} {datetime.now()}")
тогда в этом месте добавляй в атрибут `self.history` объект, который хранит инфу про текущую операцию

2023-03-31 14:09 UTC, vimoro commented on Dz_11.py
> +class OperationsHistory:
и тогда это пускай будет класс BankAccountHistory, он только хранит данные об операции, поэтому можешь сделать его дата классом

2023-03-31 14:09 UTC, vimoro commented on Dz_11.py
в целом ты на верном пути
немного только подправить работу с историей, как я написала в комментах

2023-04-03 21:07 UTC, Wasil-P commented on Dz_11.py
> +        self.last_operation = ()
Не зусім зразумеў, што маецца на ўвазе пад "полем"? Атрыбут? 
self.history: list[BankAccountHistory] = []. Такі?

2023-04-04 09:20 UTC, Wasil-P reviewed
Дзень добры.
Перарабіў. 
Гляньце калі ласка, але паходу губляецца сэнс у класе BankAccountHistory
Тое самае можна запрашываць праз BankAcc

2023-04-07 10:51 UTC, vimoro requested changes

2023-04-07 10:51 UTC, vimoro commented on Dz_11.py
> +    history: list
в этом классе должны быть атрибуты amount, operation и date_time

2023-04-07 10:51 UTC, vimoro commented on Dz_11.py
> +        self.history.append([(f"Replenishment of the balance {self.balance} {datetime.now()}")])
и вот тут тебе нужно создавать объект класса BankAccountHistory и добавлять его в список self.history

2023-04-07 10:51 UTC, vimoro commented on Dz_11.py
> +        self.history.append([(f"Withdrawal of funds from the balance {self.balance} {datetime.now()}")])
и здесь тоже

2023-04-08 13:25 UTC, Wasil-P reviewed
Перароблены Dz11

2023-04-10 21:26 UTC, vimoro approved these changes

2023-04-11 14:34 UTC, merged