Dz12
Wasil-P/Python_lessons pull request #5
Opened 2023-04-03 20:50 UTC by Wasil-P

2023-04-07 10:56 UTC, vimoro requested changes

2023-04-07 10:56 UTC, vimoro commented on Dz_11.py
этого файло не должно быть в этом пул реквесте

2023-04-07 10:56 UTC, vimoro commented on Dz_12.py
> +# answer_user = int(input('Ваш выбор: '))
вот тут может произойти исключение и значит сюда нужно добавить его обработку

2023-04-07 10:56 UTC, vimoro commented on Dz_12.py
> +# print(random_list_numbers(-4))
раз твоя функция может выбросить исключение EnteredNumberError, значит в месте, где ты её вызываешь, хорошо бы это исключение обрабатывать

2023-04-08 12:56 UTC, Wasil-P reviewed
Выдалены Dz11
Перароблены Dz12

2023-04-12 13:32 UTC, vimoro approved these changes

2023-04-14 10:27 UTC, merged