Dz13
Wasil-P/Python_lessons pull request #6
Opened 2023-04-05 21:24 UTC by Wasil-P

2023-04-06 12:43 UTC, vimoro requested changes

2023-04-06 12:43 UTC, vimoro commented on Dz_13.py
немного не то в задание сделал: у тебя сейчас генератор и итератор возвращают последовательность чисел, которая начинается с какого-то случайного числа, а нужно генерировать лучайные числа вроде: 7, 2, 10, 14, 18, 8...

2023-04-06 12:43 UTC, vimoro commented on Dz_11.py
не апрувну дз, пока в пул реквесте будут лишние файлы

2023-04-08 12:43 UTC, Wasil-P reviewed
Выдалены Dz11
Перароблены Dz13

2023-04-10 21:24 UTC, vimoro approved these changes

2023-04-13 09:05 UTC, merged